DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS customers;


-- ===============================
-- CUSTOMERS TABLE
-- ===============================
CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



-- ===============================
-- BOOKS TABLE
-- ===============================
CREATE TABLE books (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150),
    price DECIMAL(10,2) NOT NULL CHECK (price > 0),
    stock INT NOT NULL CHECK (stock >= 0),
    category VARCHAR(100)
);



-- ===============================
-- ORDERS TABLE
-- ===============================
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id INT NOT NULL,
    total_price DECIMAL(10,2) NOT NULL,

    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE
);



-- ===============================
-- ORDER ITEMS TABLE
-- (Bridge between Orders & Books)
-- ===============================
CREATE TABLE order_items (

    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id INT NOT NULL,
    book_id INT NOT NULL,

    quantity INT NOT NULL CHECK (quantity > 0),

    price DECIMAL(10,2) NOT NULL,

    CONSTRAINT fk_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_book
        FOREIGN KEY (book_id)
        REFERENCES books(id)
);
